name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache dependencies & build
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.pnpm-store
            node_modules
            .next/cache
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          sudo npm install -g pnpm
          pnpm install
      - name: Run build
        run: pnpm build --debug --no-lint
